export const API = 'https://netmeds.onrender.com/product'
export const Product_API = 'https://netmeds.onrender.com/product'
export const Cart_API = 'https://netmeds.onrender.com/cart'
export const Home_API = 'https://netmeds.onrender.com/home'
export const User_API = 'https://netmeds.onrender.com/user'
export const SaveForLater_API = 'https://netmeds.onrender.com/saveForlater'
export const Premium_API = 'https://netmeds.onrender.com/premiumMember'
